import type { Metadata } from "next";
import { Header } from "./shared";
import "./globals.css";

export const metadata: Metadata = {
  title: "Московская коллегия адвокатов Кятова, Клячковский и Партнёры",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`cygre-font antialiased text-stone-900 overflow-x-hidden w-full`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
